# {"Version":"1.3.0","Date":"","Source":"IncludeHelper","HeaderVersion":1}
# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE.

# SET MY INVOKE COMMAND ALIAS
#
# Allows calling constitely InvokeHelper with the module tag
# Need to define a variable called $MODULE_INVOKATION_TAG
#

$moduleRootPath = $PSScriptRoot | Split-Path -Parent
$MODULE_NAME = (Get-ChildItem -Path $moduleRootPath -Filter *.psd1 | Select-Object -First 1).BaseName
$MODULE_INVOKATION_TAG = "$($MODULE_NAME)Module"

function Set-MyInvokeCommandAlias{
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory,Position=0)][string]$Alias,
        [Parameter(Mandatory,Position=1)][string]$Command
    )

    if ($PSCmdlet.ShouldProcess("InvokeCommandAliasList", ("Add Command Alias [{0}] = [{1}]" -f $Alias, $Command))) {
        InvokeHelper\Set-InvokeCommandAlias -Alias $Alias -Command $Command -Tag $MODULE_INVOKATION_TAG
    }
}

function Reset-MyInvokeCommandAlias{
    [CmdletBinding(SupportsShouldProcess)]
    param()

    # throw if MODULE_INVOKATION_TAG is not set or is "MyModuleModule"
    if (-not $MODULE_INVOKATION_TAG) {
        throw "MODULE_INVOKATION_TAG is not set. Please set it to a unique value before calling Set-MyInvokeCommandAlias."
    }
    InvokeHelper\Reset-InvokeCommandAlias -Tag $MODULE_INVOKATION_TAG
}

function Invoke-MyCommand{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline,Position=0)][string]$Command,
        [Parameter(Position=1)][hashtable]$Parameters
    )

    Write-MyDebug "invoke" $Command $Parameters

    return InvokeHelper\Invoke-MyCommand -Command $Command -Parameters $Parameters
}

function Invoke-MyCommandAsync{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline,Position=0)][string]$Command,
        [Parameter(Position=1)][hashtable]$Parameters
    )

    Write-MyDebug "invoke" $Command $Parameters

    $job = InvokeHelper\Start-MyJob -Command $Command -Parameters $Parameters

    $call = [pscustomobject]@{
        Job = $job
        Command = $Command
        Parameters = $Parameters
    }

    return $call
}

function Wait-MyCommandAsync{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline,Position=0)][pscustomobject]$call
    )

    begin{
        $jobs = @()
    }

    process{

        $jobs += $call.Job

    }

    end {

        $waitingJobs = $jobs
        
        $all = $waitingJobs.Count
        "Waiting for [$all] jobs to complete " | Write-MyHost -noNewline
        
        while ($waitingJobs.Count -ne 0) {
            
            $waitings = $waitingJobs | Wait-Job -Any
            
            "." | Write-MyHost -NoNewline
            
            # Remove completed jobs from the waiting list
            $waitingJobs = $waitingJobs | Where-Object { $_.Id -ne $waitings.Id }
            
        }
        
        $completed = $jobs | Where-Object { $_.State -eq 'Completed' } | Measure-Object | Select-Object -ExpandProperty Count
        $failed = $jobs | Where-Object { $_.State -eq 'Failed' } | Measure-Object | Select-Object -ExpandProperty Count
        $all = $jobs.Count
        
        "" | Write-MyHost
        "Completed [$completed] Failed [$failed]" | Write-MyHost
    }
}

function Receive-MyCommandAsync{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline,Position=0)][pscustomobject]$call
    )

    $res = Receive-Job -Job $call.Job -ErrorAction SilentlyContinue

    # Check for false if update failed
    if(-not $res){
        "Failed calling to update project [$($call.Parameters.projectnumber)]." | Write-MyError
    } else {
        $res
    }
}

# Reset all aliases for this module on each refresh
Reset-MyInvokeCommandAlias