function Set-IncludeFileVersion{
    [CmdletBinding()]
    [outputtype([bool])]
     param(
        [parameter(Mandatory,ValueFromPipelineByPropertyName)][string]$Path,
        [parameter(Mandatory)][string]$Version,
        [parameter()][string]$Date,
        [parameter()][string]$Source
     )

     # Return of file does not exist
     if(-not (Test-Path -Path $Path)){
         throw "File $Path not found"
    }

    # initialize date
    $Date = [string]::IsNullOrEmpty($Date) ? (Get-Date).ToString("yyyy-MM-dd") : $Date

    # Read actual content
    $content = Get-Content -Path $Path

    # Get actual version
    $actualVersion = $null -eq $content ? $null : $(Get-VersionFromHeader -content $content)

    # if($actualVersion){
    #     # Check if actual version is the same as the new version, if so return true
    #     if(($actualVersion.Version -eq $Version) -and ($actualVersion.Date -eq $Date)){
    #         return $true
    #     }
    # }

    # If version remove header
    if($actualVersion){
        $content = Remove-VersionHeader -content $content
    }

    # If source not specified, get the source from the path
    if([string]::IsNullOrEmpty($Source)){
        $source = Find-ModuleRootPath -Path $Path | split-path -Leaf
    }

    # Build Target version line
     $tragetFirstLine = Build-VersionHeader -Version $Version -Date $Date -Source $source

    # Add the new version header as the first line of the file
    $newContent = @($tragetFirstLine) + $content

    # Set value and return true
    # Do not use Set-Content as it adds a last line break, use Out-File instead
    $newContent -join "`n" | Out-File -Path $Path -NoNewline
    return $true

} Export-ModuleMember -Function Set-IncludeFileVersion

$script:HEADER_V1 = @(
    '# {"Version":"{version}","Date":"{date}","Source":"{source}","HeaderVersion":{headerversion}}',
    "# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE."
)

function Build-VersionHeader_V1{
    [alias("Build-VersionHeader")]
    param(
        [string]$Version,
        [string]$Date,
        [string]$Source
    )

    $headerversion = 1
    $header = $script:HEADER_V1

    $Date = [string]::IsNullOrEmpty($Date) ? (Get-DateString) : $Date

    # replace the {json} placeholder with the actual json

    $header = $header | ForEach-Object { $_ -replace "{headerversion}", "$headerversion" }
    $header = $header | ForEach-Object { $_ -replace "{version}", $Version }
    $header = $header | ForEach-Object { $_ -replace "{date}", $Date }
    $header = $header | ForEach-Object { $_ -replace "{source}", $Source }

    return $header
} Export-ModuleMember -Function Build-VersionHeader_V1 -Alias Build-VersionHeader

function Remove-VersionHeader($content){

    $headerSizeV0 = 1
    $headersSizeV1 = $script:HEADER_V1.Count

    $version = Get-VersionFromHeader -content $content

    if(-not $version){
        throw "No version header found in content"
    }

    switch ($version.HeaderVersion){
        $null {
            $content = $content | Select-Object -Skip $headerSizeV0
        }
        1 {
            # Remove first 2 lines
            $content = $content | Select-Object -Skip $headersSizeV1
        }
        default {
            throw "Unknown version header version $($version.HeaderVersion)"
        }
    }

    return $content
} Export-ModuleMember -Function Remove-VersionHeader

function Get-VersionFromHeader($content){

    # So far the version json is always on the first line

    # Get first line
    $firstline = $content | Select-Object -First 1

    # Empty first line
    if([string]::IsNullOrWhiteSpace($firstline)){
        return $null
    }

    # Remove comment char
    $json = $firstline.Substring(1)

    try { $version = $json | ConvertFrom-Json } catch { return $null }

    return $version
} export-ModuleMember -Function Get-VersionFromHeader

