function Set-IncludeFileVersion{
    [CmdletBinding()]
    [outputtype([bool])]
     param(
         [string]$Path,
         [string]$Version,
        [string]$Date
     )

     # Return of file does not exist
     if(-not (Test-Path -Path $Path)){
         throw "File $Path not found"
    }

    # initialize date
    $Date = [string]::IsNullOrEmpty($Date) ? (Get-Date).ToString("yyyy-MM-dd") : $Date

    # Read actual content
    $content = Get-Content -Path $Path

    # Get actual version
    $actualVersion = $null -eq $content ? $null : $(Get-VersionHeader -content $content)

    if($actualVersion){
        # Check if actual version is the same as the new version, if so return true
        if(($actualVersion.Version -eq $Version) -and ($actualVersion.Date -eq $Date)){
            return $true
        }
    }

    # If version remove header
    if($actualVersion){
        $content = Remove-VersionHeader -content $content
    }

    # Build Target version line
     $tragetFirstLine = Build-VersionHeader -Version $Version -Date $Date

    # Add the new version header as the first line of the file
    $newContent = @($tragetFirstLine) + $content

    # Set value and return true
    # Do not use Set-Content as it adds a last line break, use Out-File instead
    $newContent -join "`n" | Out-File -Path $Path -NoNewline
    return $true

} Export-ModuleMember -Function Set-IncludeFileVersion


function Build-VersionHeader{
    param(
        [string]$Version,
        [string]$Date
    )

    $json = @{
        Version = $Version
        Date = $Date
        headerVersion = 1
    } | ConvertTo-Json -Depth 3 -Compress

    # Header Version 1
    $header = @()
    $header += "# $json"
    $header += "# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE."
    $header += "#"

    return $header
}

function Remove-VersionHeader($content){

    $version = Get-VersionHeader -content $content

    if(-not $version){
        throw "No version header found in content"
    }

    switch ($version.headerVersion){
        $null {
            $content = $content | Select-Object -Skip 1
        }
        1 {
            # Remove first 3 lines
            $content = $content | Select-Object -Skip 3
        }
        default {
            throw "Unknown version header version $($version.headerVersion)"
        }
    }

    return $content
}

function Get-VersionHeader($content){
    # Get first line
    $firstline = $content | Select-Object -First 1

    # Remove comment char
    $json = $firstline.Substring(1)

    try { $version = $json | ConvertFrom-Json } catch { return $null }

    return $version
}

