function Set-IncludeFileVersion{
    [CmdletBinding()]
    [outputtype([bool])]
     param(
         [string]$Path,
         [string]$Version,
        [string]$Date
     )

     # Return of file does not exist
     if(-not (Test-Path -Path $Path)){
         throw "File $Path not found"
    }

    # initialize date
    $Date = [string]::IsNullOrEmpty($Date) ? (Get-Date).ToString("yyyy-MM-dd") : $Date

    # Read actual content
    $content = Get-Content -Path $Path

    # Get actual version
    $actualVersion = $null -eq $content ? $null : $(Get-VersionHeader -content $content)

    if($actualVersion){
        # Check if actual version is the same as the new version, if so return true
        if(($actualVersion.Version -eq $Version) -and ($actualVersion.Date -eq $Date)){
            return $true
        }
    }

    # If version remove header
    if($actualVersion){
        $content = Remove-VersionHeader -content $content
    }

    # Build Target version line
     $tragetFirstLine = Build-VersionHeader -Version $Version -Date $Date

    # Add the new version header as the first line of the file
    $newContent = @($tragetFirstLine) + $content

    # Set value and return true
    # Do not use Set-Content as it adds a last line break, use Out-File instead
    $newContent -join "`n" | Out-File -Path $Path -NoNewline
    return $true

} Export-ModuleMember -Function Set-IncludeFileVersion

$script:HEADER_V1 = @(
    '# {"Version":"{version}","Date":"{date}","headerVersion":{headerVersion}}',
    "# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE."
)

function Build-VersionHeader_V1{
    [alias("Build-VersionHeader")]
    param(
        [string]$Version,
        [string]$Date
    )

    $headerversion = 1
    $header = $script:HEADER_V1
    
    # replace the {json} placeholder with the actual json

    $header = $header | ForEach-Object { $_ -replace "{headerVersion}", "$headerversion" }
    $header = $header | ForEach-Object { $_ -replace "{version}", $Version }
    $header = $header | ForEach-Object { $_ -replace "{date}", $Date }

    return $header
}

function Remove-VersionHeader($content){

    $headerSizeV0 = 1
    $headersSizeV1 = $script:HEADER_V1.Count

    $version = Get-VersionHeader -content $content

    if(-not $version){
        throw "No version header found in content"
    }

    switch ($version.headerVersion){
        $null {
            $content = $content | Select-Object -Skip $headerSizeV0
        }
        1 {
            # Remove first 2 lines
            $content = $content | Select-Object -Skip $headersSizeV1
        }
        default {
            throw "Unknown version header version $($version.headerVersion)"
        }
    }

    return $content
}

function Get-VersionHeader($content){

    # So far the version json is always on the first line

    # Get first line
    $firstline = $content | Select-Object -First 1

    # Empty first line
    if([string]::IsNullOrWhiteSpace($firstline)){
        return $null
    }

    # Remove comment char
    $json = $firstline.Substring(1)

    try { $version = $json | ConvertFrom-Json } catch { return $null }

    return $version
}

