function Test_SetFileVersion_EmptyFile{

    $version = "1.0.0"
    $source = "kk"

    touch "TestFile.ps1"

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version -Source $source

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -source $source
}

function Test_SetFileVersion_NoVersion{

    $version = "1.0.0"
    $source = "kk"

    New-Testingfile -Name "TestFile.ps1" -Content $FILE_FACKE_CONTENT

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version -Source $source

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Body $FILE_FACKE_CONTENT -Source $source
}


function Test_SetFileVersion_OnlyVersion{

    $version = "3.2.1"

    # Arrange version in file
    $headerversion = 1
    $version = "1.0.0"
    $date = "1975-02-18"
    $source = "kk"
    $json = Build-TestFileVersionJson $Version $Date $source $headerversion
    New-Testingfile -Name "TestFile.ps1" -Content $("# $json")
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Date $date -Source $source

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version -Source $source

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Source $source
}

function Test_SetFileVersion_VersionAndBody{

    $version = "3.2.1"
    $source = "kk"

    # Arrange version in file
    $headerversion = 1
    $version = "1.0.0"
    $date = "1975-02-18"
    $json = Build-TestFileVersionJson $Version $Date $source $headerversion
    New-Testingfile -Name "TestFile.ps1" -Content $("# $json")
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Date $date -Source $source

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version -Source $source

    # Assert
    Assert-IsTrue -Condition $result
    Enable-IncludeHelperDebug -Section "Assert-FileVersion"
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Body $body -Source $source
    Disable-IncludeHelperDebug
}

$FILE_FACKE_CONTENT = @'
# This is text
# Not sure if I will


morethings or less
'@

function Assert-FileVersion{
    param(
        [string]$Path,
        [string]$Version,
        [string]$Date = (Get-Date -Format "yyyy-MM-dd"),
        [string]$Body,
        [string]$Source = "IncludeHelper"
    )

    $headerversion = 1
    $headeersizeinlines = $script:TEST_HEADER_V1.Count

    $content = (Get-Content -Path $Path) -join  "`n"
    $json = Build-TestFileVersionJson $Version $Date $Source $headerversion
    $expected = "# $json"

    $content = @(Get-Content -Path $Path)
    # "Content of file $Path :" | Write-MyDebug -Section "Assert-FileVersion" -Object $content

    # Assert first line
    Assert-AreEqual -Expected $expected -Presented $content[0]

    # Assert content if provided
    if(-not [string]::IsNullOrWhiteSpace($Body)){
        # "Comparing body" | Write-MyDebug -Section "Assert-FileVersion"
        
        # Remove header from content to compare with body
        $rest = $content | Select-Object -Skip $headeersizeinlines
        $rest = $rest -join "`n"

        Assert-AreEqual -Expected $Body -Presented $rest 
    }
}

function Build-TestFileVersionJson($Version, $Date, $Source, $Headerversion){

    # Need to create the full object to control the order of members for mocking
    if(-not [string]::IsNullOrWhiteSpace($Headerversion)){
        $json = [pscustomobject]@{
            Version = $Version
            Date = $Date
            Source = $Source
            HeaderVersion = $Headerversion
        }
    } else {
        $json = [pscustomobject]@{
            Version = $Version
            Date = $Date
        }
    }
    
    $ret = $json | ConvertTo-Json -Depth 3 -Compress

    return $ret
}

$script:TEST_HEADER_V1 = @(
    '# {"Version":"{version}","Date":"{date}","Source":"{source}","HeaderVersion":{headerversion}}',
    "# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE."
)

function Build-TestVersionHeader($version, $Date, $source,$headerversion){
    # Sync this code with Build-VersionHeader at public/setfileversion.ps1

    $headerversion = $headerversion
    $header = $script:TEST_HEADER_V1
    
    # replace the {json} placeholder with the actual json

    $header = $header | ForEach-Object { $_ -replace "{headerversion}", "$headerversion" }
    $header = $header | ForEach-Object { $_ -replace "{source}", "IncludeHelper" }
    $header = $header | ForEach-Object { $_ -replace "{version}", $Version }
    $header = $header | ForEach-Object { $_ -replace "{date}", $Date }

    return $header
}