function Test_SetFileVersion_EmptyFile{

    $version = "1.0.0"

    touch "TestFile.ps1"

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version
}

function Test_SetFileVersion_NoVersion{

    $version = "1.0.0"

    New-Testingfile -Name "TestFile.ps1" -Content $FILE_FACKE_CONTENT

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Body $FILE_FACKE_CONTENT
}


function Test_SetFileVersion_OnlyVersion{

    $version = "3.2.1"

    # Arrange version in file
    $headerversion = 1
    $version = "1.0.0"
    $date = "1975-02-18"
    $json = Build-TestFileVersionJson $Version $Date $headerversion
    New-Testingfile -Name "TestFile.ps1" -Content $("# $json")
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Date $date

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version

    # Assert
    Assert-IsTrue -Condition $result
    Assert-FileVersion -Path "TestFile.ps1" -Version $version
}

function Test_SetFileVersion_VersionAndBody{

    $version = "3.2.1"

    # Arrange version in file
    $headerversion = 1
    $version = "1.0.0"
    $date = "1975-02-18"
    $json = Build-TestFileVersionJson $Version $Date $headerversion
    New-Testingfile -Name "TestFile.ps1" -Content $("# $json")
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Date $date

    # Act
    $result = Set-IncludeFileVersion -Path "TestFile.ps1" -Version $version

    # Assert
    Assert-IsTrue -Condition $result
    Enable-IncludeHelperDebug -Section "Assert-FileVersion"
    Assert-FileVersion -Path "TestFile.ps1" -Version $version -Body $body
    Disable-IncludeHelperDebug
}

$FILE_FACKE_CONTENT = @'
# This is text
# Not sure if I will


morethings or less
'@

function Assert-FileVersion{
    param(
        [string]$Path,
        [string]$Version,
        [string]$Date = (Get-Date -Format "yyyy-MM-dd"),
        [string]$Body
    )

    $headerversion = 1
    $headeersizeinlines = $script:TEST_HEADER_V1.Count

    $content = Get-Content -Path $Path | Out-String
    $json = Build-TestFileVersionJson $Version $Date "IncludeHelper" $headerversion
    $expected = "# $json"

    $content = @(Get-Content -Path $Path)
    # "Content of file $Path :" | Write-MyDebug -Section "Assert-FileVersion" -Object $content

    # Assert first line
    Assert-AreEqual -Expected $expected -Presented $content[0]

    # Assert content if provided
    if(-not [string]::IsNullOrWhiteSpace($Body)){
        # "Comparing body" | Write-MyDebug -Section "Assert-FileVersion"
        # Remove the first line from content
        $rest = $content | Select-Object -Skip $headeersizeinlines
        # join string[] to string
        $rest = $rest -join "`n"
        # "Body presented:" | Write-MyDebug -Section "Assert-FileVersion" -Object $Body
        # "Rest Content :" | Write-MyDebug -Section "Assert-FileVersion" -Object $rest
        Assert-AreEqual -Expected $Body -Presented $rest -Comment "Rest of the file content should be the same"
    }
}

function Build-TestFileVersionJson($Version, $Date, $Source, $Headerversion){

    # Need to create the full object to control the order of members for mocking
    if(-not [string]::IsNullOrWhiteSpace($Headerversion)){
        $json = [pscustomobject]@{
            Version = $Version
            Date = $Date
            Source = "IncludeHelper"
            HeaderVersion = $Headerversion
        }
    } else {
        $json = [pscustomobject]@{
            Version = $Version
            Date = $Date
        }
    }
    
    $ret = $json | ConvertTo-Json -Depth 3 -Compress

    return $ret
}

$script:TEST_HEADER_V1 = @(
    '# {"Version":"{version}","Date":"{date}", "Source":"{source}","HeaderVersion":{headerversion}}',
    "# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE."
)

function Build-TestVersionHeader($version, $Date, $headerversion){
    # Sync this code with Build-VersionHeader at public/setfileversion.ps1

    $headerversion = $headerversion
    $header = $script:TEST_HEADER_V1
    
    # replace the {json} placeholder with the actual json

    $header = $header | ForEach-Object { $_ -replace "{headerversion}", "$headerversion" }
    $header = $header | ForEach-Object { $_ -replace "{source}", "IncludeHelper" }
    $header = $header | ForEach-Object { $_ -replace "{version}", $Version }
    $header = $header | ForEach-Object { $_ -replace "{date}", $Date }

    return $header
}