# {"Version":"1.1.1","Date":"2026-08-13","Source":"NotesHelper","HeaderVersion":1}
# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE.
# Register-ArgumentCompleter
#
# To control the parametrs autofil we can register a scriptblock variable with a function to manage 
# the parametrs. this function should return the possible values.
# Use ConvertTo-CompleteResults to generate the output objects from a list of valid strings
#
# # Sample code 1: Get param values from script
#
# Register-ArgumentCompleter -CommandName <CommandName> -ParameterName <ParameterName> -ScriptBlock $ValidParameterValues
#
# $ValidParameterValues = {
#      param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
#
#     $list = @(
#         "Value1",
#         "Value2",
#         "Value3"
#     )
#
#     $list | ConvertTo-CompleteResults -wordToComplete $wordToComplete
# }
#
# # Sample code 2: Get param values from function
#
# Register-ArgumentCompleter -CommandName <CommandName> -ParameterName <ParameterName> -ScriptBlock { param($commandName, $parameterName, $wordToComplete, $commandAst) Get-ParamFunction @PsBoundParameters }
#
# function Get-ParamFunction{
#     param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
#     $list = @(
#         "Value1",
#         "Value2",
#         "Value3"
#     )
#     $list | ConvertTo-CompleteResults -wordToComplete $wordToComplete
# }
#
# # Sample code 3: Param with dependency of a different param
#
# Register-ArgumentCompleter -CommandName <CommandName> -ParameterName <ParameterName> -ScriptBlock { param($commandName, $parameterName, $wordToComplete, $commandAst) Get-ParamFunction @PsBoundParameters }
#
# function Get-ParamFunction{
#     param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
#
#    $dependParameterValue = getParameterValue -commandAst $commandAst -ParameterName "DependParameter" -ParameterAlias "dp"
#
#    $list = Get-ValuesBasedOnDependParameter -DependParameterValue $dependParameterValue
#
#    $list | ConvertTo-CompleteResults -wordToComplete $wordToComplete
# }

function ConvertTo-CompleteResults{
    param(
        [parameter(Mandatory, ValueFromPipeline,Position=0)][string[]]$Values,
        [string]$wordToComplete,
        [switch]$StartWith
    )

    begin {
        $pattern = $StartWith.IsPresent ? "$wordToComplete*" : "*$wordToComplete*"

        $list = @()
    }

    process{
        $list += $Values
    }

    end{

        "Processing $($list.Count) values for completion with pattern '$pattern'" | Write-Mydebug -Section "ArgumentCompleter"

        $ret = $list | Where-Object { $_ -like $pattern } | Select-Object -Unique
        
        "Returning $($ret.Count) values matching '$pattern'" | Write-Mydebug -Section "ArgumentCompleter" -object $ret

        $ret = $ret | addQuotesIfSpaces

        $ret | ForEach-Object { [System.Management.Automation.CompletionResult]::new( $_, $_, 'ParameterValue', $_) }
    }
}

function addQuotesIfSpaces {
    param(
        [parameter(Mandatory, ValueFromPipeline,Position=0)][string]$Value
    )

    process{

        if($Value -like "* *"){
            "Adding quotes to value '$Value'" | Write-Mydebug -Section "ArgumentCompleter"
            return "`"$Value`""
        }
        else{
            return $Value
        }
    }
}

# Parse CommandText to find the value of an already filled parameter.
# Checks for parameter alias too.
function getParameterValue {
    param(
        [System.Management.Automation.Language.CommandAst]$commandAst,
        [string]$ParameterName,
        [string]$ParameterAlias
    )

    $CommandText = $commandAst.Extent.Text
    
    # Match parameter followed by either quoted string or unquoted word
    if ($CommandText -match "-$ParameterName\s+(?:(?:`"([^`"]*)`")|(?:'([^']*)')|([^\s-]+))") {
        return $matches[1], $matches[2], $matches[3] | Where-Object { $_ }
    }
    
    # If ParameterName not found, try ParameterAlias
    if ($ParameterAlias -and $CommandText -match "-$ParameterAlias\s+(?:(?:`"([^`"]*)`")|(?:'([^']*)')|([^\s-]+))") {
        return $matches[1], $matches[2], $matches[3] | Where-Object { $_ }
    }
    
    return $null
}